version: "3.4"

services:
  diplom-db:
    image: ${COMPOSE_PROJECT_NAME}-db:$BUILD_NUMBER
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
         POSTGRES_DB: face_recog_db
         POSTGRES_USER: persik
         POSTGRES_PASSWORD: qwerty123
    restart: always
    env_file: .env
    volumes:
      - ./pg:/var/lib/postgresql/data/
#    ports:
#      - 5440:5432

  diplom-django-server:
    image: ${COMPOSE_PROJECT_NAME}-django:$BUILD_NUMBER
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./diplom:/app
    depends_on:
      - diplom-db
    ports:
      - 8000:8000

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=diplom-db
    ports:
      - 8080:8080