# Generated by Django 2.2 on 2020-03-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200309_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedobject',
            name='img_height',
            field=models.PositiveIntegerField(default=480, null=True),
        ),
        migrations.AlterField(
            model_name='recognizedobject',
            name='img_width',
            field=models.PositiveIntegerField(default=640, null=True),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='img_height',
            field=models.PositiveIntegerField(default=480, null=True),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='img_width',
            field=models.PositiveIntegerField(default=640, null=True),
        ),
    ]
